import NavigationBar from "../../components/containers/navigationbar/navigationBar";
import React, { useState } from "react";
import Head from "next/head";
import Zoom from "../../components/Zoom";
import { Row, Col, Grid, Badge, Button } from "@nextui-org/react";
import NavAfterLogin from "../../components/containers/navigationbar/navAfterLogin";
import { auth } from "../../firebase";
const ProductDetail = () => {
  const images = [
    {
      id: 1,
      value: "/keyboard/1.jpg",
    },
    {
      id: 2,
      value: "/keyboard/2.jpg",
    },
    {
      id: 3,
      value: "/keyboard/3.jpg",
    },
    {
      id: 4,
      value: "/keyboard/4.jpg",
    },
  ];

  const [mainImg, setMainImg] = useState(images[0]);

  const handleClick = (index) => {
    const image = images[index];
    setMainImg(image);
    console.log(index);
  };

  const user = auth.currentUser;
  return (
    <>
      <Head>
        <title>Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{user ? <NavAfterLogin /> : <NavigationBar />}</div>
      <div style={{ marginTop: 50, marginBottom: 50 }}>
        <Grid.Container gap={2} justify="center">
          <Grid xl={3} lg={3} sm={6} md={6} xs={12}>
            <Col xl={3} lg={3} sm={6} md={6} xs={12}>
              <div style={{ maxWidth: "100%", maxHeight: "100%" }}>
                <Zoom src={mainImg.value} />
              </div>

              <Grid.Container gap={1} justify="flex-start">
                {images.map((data, i) => (
                  <Grid key={i} xl={3} lg={3} sm={3} md={3} xs={3}>
                    <img
                      src={data.value}
                      onClick={() => handleClick(i)}
                      height="100%"
                      width="100%"
                    />
                  </Grid>
                ))}
              </Grid.Container>
            </Col>
          </Grid>

          <Grid xl={3} lg={3} sm={6} md={6} xs={12}>
            <Col>
              <div
                style={{
                  width: "100%",
                }}
              >
                <Row>
                  <h2 style={{ marginTop: "0" }}>Royal Kludge keybaord 60%</h2>
                </Row>
                <Row css={{ mt: 15, mb: 15 }}>
                  <Badge
                    color="secondary"
                    size="xl"
                    isSquared
                    variant="bordered"
                  >
                    35 $
                  </Badge>
                </Row>
                <Row css={{ mt: 15 }}>
                  <h5 style={{ margin: "10px 0", fontWeight: 700 }}>
                    PRODUCT DETAILS
                  </h5>
                </Row>
                <Row css={{ mb: 15 }}>
                  <p style={{ margin: "0px" }}>red switch great conditions</p>
                </Row>
                <Row css={{ mt: 5 }}>
                  <h5 style={{ margin: "10px 0", fontWeight: 700 }}>
                    SELLER DETAILS
                  </h5>
                </Row>
                <Row css={{ mb: 10 }}>
                  <p style={{ margin: "0px" }}>Phone Number : </p>
                  <p style={{ marginLeft: "10px" }}> 0987654321 </p>
                </Row>
              </div>
            </Col>
          </Grid>
        </Grid.Container>
      </div>
    </>
  );
};

export default ProductDetail;
